services:
  face-unlock:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./known_faces:/app/known_faces
      - ./static:/app/static
      - ./templates:/app/templates
      # SOLUCIÓN CÁMARA WINDOWS
      - /dev:/dev
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    stdin_open: true
    tty: true
    # ACCESO CÁMARA - CRÍTICO
    privileged: true
    devices:
      - /dev/video0:/dev/video0
    # ALTERNATIVA WINDOWS
    #network_mode: host